// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace cmsDb2024_System.Models
{
    public partial class AsignacionMobilTecnico
    {
        public int Id { get; set; }
        public string Mac { get; set; }
        public string Coduser { get; set; }
        public DateTime Fecrea { get; set; }
    }
}