// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace cmsDb2024_System.Models
{
    public partial class AsignacionUsuarioBodega
    {
        public int Id { get; set; }
        public DateTime? Fecrea { get; set; }
        public string Iduser { get; set; }
        public int? Idbodega { get; set; }
        public string Usercrea { get; set; }
        public string Ccia { get; set; }
        public int? Estado { get; set; }
        public string UrlImagenFirma { get; set; }
    }
}