// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace cmsDb2024_System.Models
{
    public partial class IntervalosTicketMsj
    {
        public int IdIntervaloMsj { get; set; }
        public int? IdIntervalo { get; set; }
        public DateTime Fecrea { get; set; }
        public int? IdMensaje { get; set; }
    }
}