// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace cmsDb2024_System.Models
{
    public partial class Localidad
    {
        public int Id { get; set; }
        public string NombreLocalidad { get; set; }
        public string Descripcion { get; set; }
    }
}