// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace cmsDb2024_System.Models
{
    public partial class Localidadcobertura
    {
        public int? Idlocalidad { get; set; }
        public int Idcoberturalocal { get; set; }
        public string Codprovincia { get; set; }
        public string Descripcion { get; set; }
    }
}