// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace cmsDb2024_System.Models
{
    public partial class Mensajeria
    {
        public string Codigomensaje { get; set; }
        public DateTime? Feccrea { get; set; }
        public string Titulo { get; set; }
        public string Mensaje { get; set; }
        public string Coduser { get; set; }
        public string Codremitente { get; set; }
        public int? Estado { get; set; }
        public string Tipo { get; set; }
    }
}