// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace cmsDb2024_System.Models
{
    public partial class ModuleMobile
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string Icon { get; set; }
        public string Color { get; set; }
        public string Codec { get; set; }
        public int? Estado { get; set; }
        public int? Permisos { get; set; }
        public string Ccia { get; set; }
        public string CodecNavigate { get; set; }
    }
}