// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace cmsDb2024_System.Models
{
    public partial class ObtenerTicketsRequerimientosResult
    {
        public int idTicket { get; set; }
        public string tiempoTotalExactoMinutos { get; set; }
        public int? cantRep { get; set; }
        public string usercrea { get; set; }
        public string idAgencia { get; set; }
        public string url { get; set; }
        public string estado { get; set; }
        public string codprov { get; set; }
        public string ciudad { get; set; }
        public DateTime? fecrea { get; set; }
        public DateTime? fechainiPlanif { get; set; }
        public DateTime? fechafinPlanif { get; set; }
        public int? contadorinicial { get; set; }
        public int? contadorfinal { get; set; }
        public string codmaquina { get; set; }
        public string codModelo { get; set; }
        public string area { get; set; }
        public string motivoTrabajo { get; set; }
        public string espacioSirve { get; set; }
        public string descripcionProblema { get; set; }
        public string nserieEquipo { get; set; }
        public string beneficiario { get; set; }
        public string telefono { get; set; }
        public string email { get; set; }
        public DateTime? fecreaRealIni { get; set; }
        public DateTime? fecreaRealFin { get; set; }
        public string codTipoEquipo { get; set; }
        public string tipoRequerimiento { get; set; }
        public TimeSpan horaInicialReal { get; set; }
        public TimeSpan horaFinalReal { get; set; }
        public TimeSpan horaInicialPlanificada { get; set; }
        public TimeSpan horaFinalPlanificada { get; set; }
        public string nombreAgencia { get; set; }
        public string codcliente { get; set; }
        public string codfrecuencia { get; set; }
        public string nombreCliente { get; set; }
        public string correomantenimiento { get; set; }
        public string nombreProvincia { get; set; }
        public string nombreCanton { get; set; }
        public string nombreTipoRequerimiento { get; set; }
        public DateTime fechaActual { get; set; }
        public int? horasRestantes { get; set; }
        public decimal valor { get; set; }
        public string observacion { get; set; }
        public string imagenRequerimiento { get; set; }
        public string imagen { get; set; }
        public int? fileCotiza { get; set; }
        public int? fileRepTec { get; set; }
        public int? fileNotEnt { get; set; }
        public string nombreMarca { get; set; }
    }
}
