// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace cmsDb2024_System.Models
{
    public partial class ObtenerRepuestosRequerimientosResult
    {
        public int? id { get; set; }
        public string codrep { get; set; }
        public int? idRequer { get; set; }
        public DateTime? fecrea { get; set; }
        public int? estado { get; set; }
        public string usercrea { get; set; }
        public string codcia { get; set; }
        public int? cantidad { get; set; }
        public decimal? valorFinal { get; set; }
        public string precioUnitario { get; set; }
        public string nombreUsuario { get; set; }
        public string nombreRep { get; set; }
        public int? marcaRep { get; set; }
        public string marcaRepuesto { get; set; }
        public string colorEstado { get; set; }
        public string nombreAgencia { get; set; }
        public string idcli { get; set; }
        public string nombreCliente { get; set; }
        public string codigoRepuesto { get; set; }
        public string descripcionRepuesto { get; set; }
        public int? idTicket { get; set; }
        public string descripcionRequerimiento { get; set; }
        public string correomantenimiento { get; set; }
        public int? idResManten { get; set; }
    }
}
