// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace cmsDb2024_System.Models
{
    public partial class ObtenerCantidadAgenciasProvResult
    {
        public string nombre { get; set; }
        public int? cantidadAgencias { get; set; }
    }
}
