// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace cmsDb2024_System.Models
{
    public partial class SettingsGeoLocalizacionMobil
    {
        public int Id { get; set; }
        public string Codmac { get; set; }
        public decimal? TimeSendDataGeoLocalization { get; set; }
        public TimeSpan? HorarioLaboinicial { get; set; }
        public TimeSpan? HorarioLabofinal { get; set; }
        public decimal? AproximGeoLocalizacion { get; set; }
        public int? MetodoDeEnvioDeDatos { get; set; }
        public int? Permisos { get; set; }
        public DateTime Fecrea { get; set; }
        public string Usercrea { get; set; }
        public int? Pasos { get; set; }
        public string ColorRutaTrazado { get; set; }
    }
}