// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ticketsRequerimientosBackend.Models;

public partial class AsignacionTecnicoTicket
{
    public int IdAsignacionTecnico { get; set; }

    public int? IdRequerimiento { get; set; }

    public string ResTecnico { get; set; }

    public string UrlA { get; set; }

    public string UrlB { get; set; }

    public string CodTenicUser { get; set; }

    public DateTime? Fechacrea { get; set; }

    public DateTime? Fechares { get; set; }

    public int? Reasignacion { get; set; }

    public TimeSpan? HoraIni { get; set; }

    public TimeSpan? Horafin { get; set; }

    public DateTime? FechaIni { get; set; }

    public DateTime? FechaFin { get; set; }
}