// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ticketsRequerimientosBackend.Models;

public partial class Auditoria
{
    public string Codaudit { get; set; }

    public string Accion { get; set; }

    public int? Codmodulo { get; set; }

    public string Codusuario { get; set; }

    public string Cod { get; set; }

    public string Ip { get; set; }

    public DateTime Fecrea { get; set; }

    public string Data { get; set; }

    public string Systemobserv { get; set; }

    public int? Estado { get; set; }
}