// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ticketsRequerimientosBackend.Models;

public partial class CabCotiza
{
    public int Id { get; set; }

    public string Codcli { get; set; }

    public DateTime Feccrea { get; set; }

    public decimal? Total { get; set; }

    public int? IdRepoTec { get; set; }

    public string Usercrea { get; set; }

    public int? Estado { get; set; }

    public int? IdResManten { get; set; }

    public string CodUserAprueba { get; set; }

    public DateTime FechaAprueba { get; set; }
}