// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ticketsRequerimientosBackend.Models
{
    public partial class CalcularTiemposPorRequerimientoResult
    {
        public int? EstadoInicial { get; set; }
        public int? EstadoFinal { get; set; }
        public decimal? TiempoTranscurrido { get; set; }
        public string TiempoFormateado { get; set; }
        public DateTime? FechaInicio { get; set; }
        public DateTime? FechaFin { get; set; }
        public string Descripcion { get; set; }
    }
}
