// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ticketsRequerimientosBackend.Models
{
    public partial class CantidadAgenMaquiResult
    {
        public string nombreCliente { get; set; }
        public string nombreAgencia { get; set; }
        public int? cantidadMaquinaria { get; set; }
    }
}
