// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ticketsRequerimientosBackend.Models;

public partial class Commandline
{
    public int Id { get; set; }

    public string CommandLineName { get; set; }

    public DateTime Fecrea { get; set; }

    public int? Estados { get; set; }

    public int? Permisos { get; set; }
}