// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ticketsRequerimientosBackend.Models;

public partial class ConfiguracionesInterfazApp
{
    public int Id { get; set; }

    public string NombreConf { get; set; }

    public string DescripcionConf { get; set; }

    public string IdMaster { get; set; }

    public int? Estado { get; set; }

    public int? Permiso { get; set; }

    public string Codcli { get; set; }

    public DateTime Fecrea { get; set; }

    public string Usercrea { get; set; }

    public string Ccia { get; set; }
}