// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ticketsRequerimientosBackend.Models;

public partial class ConfigSystem
{
    public int Id { get; set; }

    public DateTime Fecrea { get; set; }

    public int? Sethoursignal { get; set; }

    public string Usercrea { get; set; }
}