// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ticketsRequerimientosBackend.Models;

public partial class CotizaCab
{
    public int Id { get; set; }

    public string Codagencia { get; set; }

    public int? Estado { get; set; }

    public DateTime Fecrea { get; set; }

    public string Usercrea { get; set; }

    public int? Idrequer { get; set; }
}