// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ticketsRequerimientosBackend.Models;

public partial class CotizaDetail
{
    public int Id { get; set; }

    public string Codrep { get; set; }

    public int? Idcab { get; set; }

    public int? Cantidad { get; set; }

    public int? Estado { get; set; }
}