// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ticketsRequerimientosBackend.Models;

public partial class EmailSettings
{
    public int Id { get; set; }

    public int? IdEmailCliSets { get; set; }

    public string ProfileName { get; set; }

    public string EmailsToSend { get; set; }

    public DateTime? Fecrea { get; set; }

    public string Usercrea { get; set; }
}