// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ticketsRequerimientosBackend.Models;

public partial class EmailCliSet
{
    public int Id { get; set; }

    public string ProfileName { get; set; }

    public string Recipients { get; set; }

    public string Body { get; set; }

    public string Subject { get; set; }

    public string FromAddress { get; set; }

    public string ReplyTo { get; set; }

    public string Usercrea { get; set; }

    public DateTime Fecrea { get; set; }

    public string Codcli { get; set; }

    public int? Idconfig { get; set; }

    public string CodecProcess { get; set; }
}