// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ticketsRequerimientosBackend.Models
{
    public partial class GenerarAutorizacionResult
    {
        public int idTicket { get; set; }
        public string idAgencia { get; set; }
        public string nombreAgencia { get; set; }
        public string nombreCliente { get; set; }
        public string url { get; set; }
        public int? estado { get; set; }
        public string nombreProvincia { get; set; }
        public string nombreCiudad { get; set; }
        public DateTime? fecrea { get; set; }
        public DateTime? fechainiPlanif { get; set; }
        public DateTime? fechafinPlanif { get; set; }
        public string area { get; set; }
        public string motivoTrabajo { get; set; }
        public string espacioSirve { get; set; }
        public string descripcionProblema { get; set; }
        public string nserieEquipo { get; set; }
        public string beneficiario { get; set; }
        public string telefono { get; set; }
        public string email { get; set; }
        public DateTime? fecreaRealIni { get; set; }
        public DateTime? fecreaRealFin { get; set; }
        public string codTipoEquipo { get; set; }
        public string codMarca { get; set; }
        public string codModelo { get; set; }
        public string tipo { get; set; }
        public TimeSpan? horaInicialReal { get; set; }
        public TimeSpan? horaFinalReal { get; set; }
        public TimeSpan? horaInicialPlanificada { get; set; }
        public TimeSpan? horaFinalPlanificada { get; set; }
        public decimal? valorTicketRequerimiento { get; set; }
        public string observacion { get; set; }
        public string nombreEmpresa { get; set; }
        public string telefonoEmpresa { get; set; }
        public string webEmpresa { get; set; }
        public string nombreTecino { get; set; }
        public string nombremarca { get; set; }
        public string nombremodelo { get; set; }
        public string imagenCliente { get; set; }
        public string imagenTecnicoPerfil { get; set; }
        public string cedulaTecnico { get; set; }
    }
}
