// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ticketsRequerimientosBackend.Models;

public partial class IntervalosTicket
{
    public int IdIntervalo { get; set; }

    public int? Mintime { get; set; }

    public DateTime Fecrea { get; set; }

    public string Usercrea { get; set; }

    public int? Tipo { get; set; }

    public int? IdRequerimiento { get; set; }

    public int? EstadoTicket { get; set; }

    public string Observacion { get; set; }
}