// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ticketsRequerimientosBackend.Models;

public partial class MacMobilUser
{
    public int Id { get; set; }

    public string Mac { get; set; }

    public string Coduser { get; set; }

    public int? Estado { get; set; }

    public string Longitud { get; set; }

    public string Latitud { get; set; }
}