// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ticketsRequerimientosBackend.Models
{
    public partial class ObtenerCronoMobilTecnicoResult
    {
        public string codcrono { get; set; }
        public string codagencia { get; set; }
        public string codusertecnic { get; set; }
        public string nombreAgencia { get; set; }
        public string codcliente { get; set; }
        public string horarioatenciond { get; set; }
        public string imagenCliente { get; set; }
        public string horarioatencionhm { get; set; }
        public string nombreCliente { get; set; }
        public string provinciaAgencia { get; set; }
        public string cantonAgencia { get; set; }
        public DateTime? feccrea { get; set; }
        public string codusercreacrono { get; set; }
        public int? mes { get; set; }
        public int? dia { get; set; }
        public int? anio { get; set; }
        public string nombreTecnico { get; set; }
        public DateTime? fechamantenimiento { get; set; }
        public string codlocalidad { get; set; }
        public int? estado { get; set; }
        public int? cantidadAsignaciones { get; set; }
        public int? idRequer { get; set; }
        public string tipoMaquinaria { get; set; }
        public string marcaMaquinaria { get; set; }
        public string modeloMaquinaria { get; set; }
        public string descripcionProblema { get; set; }
        public TimeSpan? horaInicialReal { get; set; }
        public TimeSpan? horaFinalReal { get; set; }
        public DateTime? fecreaRealIni { get; set; }
        public DateTime? fecreaRealFin { get; set; }
        public string nombreCreadorCrono { get; set; }
        public string imagenTicketClienteGenerada { get; set; }
        public int? idAsignacionTecnico { get; set; }
    }
}
