// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ticketsRequerimientosBackend.Models
{
    public partial class ObtenerLocalidadesAgenciaResult
    {
        public string imagenPerfil { get; set; }
        public string nombreCompleto { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string telf { get; set; }
        public string email { get; set; }
        public string cedula { get; set; }
        public string codLicencia { get; set; }
        public string nombreLicencia { get; set; }
        public string nombreEstado { get; set; }
        public string nombreProvincia { get; set; }
        public string nombreCanton { get; set; }
        public string nombreCargo { get; set; }
        public string nombreMovilidad { get; set; }
        public string nombreCapacidad { get; set; }
        public string nombreSexo { get; set; }
        public string nombreEstadoCivil { get; set; }
        public string nombreDepartamento { get; set; }
        public string coduser { get; set; }
        public string fecingreso { get; set; }
        public string fecsalida { get; set; }
        public string edad { get; set; }
        public string tipo { get; set; }
        public string valoracion { get; set; }
        public string direccion { get; set; }
        public string nombreAgencia { get; set; }
        public string descripcionCobertura { get; set; }
        public string codprov { get; set; }
    }
}
