// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ticketsRequerimientosBackend.Models
{
    public partial class ObtenerAsignacionUsuarioBodegaResult
    {
        public int id { get; set; }
        public DateTime? fecrea { get; set; }
        public string iduser { get; set; }
        public int? idbodega { get; set; }
        public string usercrea { get; set; }
        public string ccia { get; set; }
        public int? estado { get; set; }
        public string urlImagenFirma { get; set; }
        public string nombreUsuarioAsignado { get; set; }
        public string nombrebodega { get; set; }
        public string nombreUsuarioCreador { get; set; }
    }
}
