// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ticketsRequerimientosBackend.Models
{
    public partial class obtenerDatosAgenciaResult
    {
        public int? idLocalidad { get; set; }
    }
}
