// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ticketsRequerimientosBackend.Models
{
    public partial class ReporteTecnicoCorrectivoResult
    {
        public int idTicket { get; set; }
        public string serieTicket { get; set; }
        public string idAgencia { get; set; }
        public string nombreCliente { get; set; }
        public string nombreAgencia { get; set; }
        public string nombreTecnico { get; set; }
        public string cedulaTecnico { get; set; }
        public string estadoEquipo { get; set; }
        public string espacioSirve { get; set; }
        public string provinciaAgencia { get; set; }
        public string tipoMantenimientoCorto { get; set; }
        public string nSerieEquipo { get; set; }
        public string tipoMaquina { get; set; }
        public string capacidad { get; set; }
        public string marca { get; set; }
        public string modelo { get; set; }
        public int? contadorinicial { get; set; }
        public int? contadorfinal { get; set; }
        public string codigobp { get; set; }
        public string ninventario { get; set; }
        public string direccion { get; set; }
        public string telf1 { get; set; }
        public string telf2 { get; set; }
        public string email { get; set; }
        public string observacion { get; set; }
        public DateTime? fechainiPlanif { get; set; }
        public DateTime? fechafinPlanif { get; set; }
        public DateTime? fecreaRealIni { get; set; }
        public DateTime? fecreaRealFin { get; set; }
    }
}
