// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ticketsRequerimientosBackend.Models;

public partial class RepuestosRespaldo
{
    public string Codrep { get; set; }

    public string NombreRep { get; set; }

    public string Codigo { get; set; }

    public string UrlimagenA { get; set; }

    public string Fecrea { get; set; }

    public string Usercrea { get; set; }

    public string Descripcion { get; set; }

    public string Marca { get; set; }

    public string CodModelo { get; set; }

    public string Activo { get; set; }

    public string MarcaRep { get; set; }

    public double? Estado { get; set; }

    public string CodTipoMaquina { get; set; }

    public string Codcia { get; set; }

    public double? CantRep { get; set; }

    public double? ValorCompra { get; set; }

    public string PorcentajeVenta { get; set; }

    public string DesccuentoAplicable { get; set; }

    public string Vidautil { get; set; }

    public string Observacion { get; set; }

    public string Modelo { get; set; }
}