// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ticketsRequerimientosBackend.Models;

public partial class ResumenMantenimiento
{
    public int Id { get; set; }

    public int? IdRequerimiento { get; set; }

    public DateTime? Fecrea { get; set; }

    public string CodResuMante { get; set; }

    public string SolucionImplementada { get; set; }

    public string Usercrea { get; set; }

    public string EstadoEquip { get; set; }

    public decimal? Valor { get; set; }

    public string Observacion { get; set; }

    public int? Estado { get; set; }
}