// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ticketsRequerimientosBackend.Models;

public partial class TaskSettings
{
    public int Id { get; set; }

    public string TaskSettings1 { get; set; }

    public string IdCliente { get; set; }

    public string Codmaster { get; set; }

    public int? Estado { get; set; }

    public int? Permiso { get; set; }

    public string Descripcion { get; set; }

    public int? IdSubTask { get; set; }
}